"""
writer.py — LLM-powered text generation for reasons and itineraries.
Strict validation: Any numbers generated by the model must strictly match
the planner data. If the model hallucinates numbers or fails, it falls back
to rich, verified templates.
"""
import re
from app.llm import chat
from app.models.schema import DatePlan, PlannedStop


def _numbers_in(text: str) -> set[int]:
    """Extract integer numbers from text."""
    return {int(n) for n in re.findall(r"\b\d+\b", text)}


async def write_why_picked(stop: PlannedStop, shared_vibes: list[str], shared_cuisines: list[str]) -> str:
    """Generate concise, factual 'Why we picked this' explanation without hallucinating."""
    vibe_overlap = [v for v in shared_vibes if v.lower() in [vt.lower() for vt in stop.venue.vibe_tags]]
    cuisine_overlap = [c for c in shared_cuisines if c.lower() in [ct.lower() for ct in stop.venue.cuisine_tags]]

    prompt = f"""Write ONE concise, romantic sentence (max 22 words) explaining why {stop.venue.name} in {stop.venue.area} was chosen for the {stop.slot.value} slot.
Factual context:
- Vibe tags: {', '.join(stop.venue.vibe_tags)}
- Shared vibes with couple: {', '.join(vibe_overlap) if vibe_overlap else 'cozy ambience'}
- Rating: {stop.venue.rating}/5.0
- Cost for two: ₹{stop.cost}
Rules: Do NOT invent facts or change the price."""

    text = await chat(prompt)
    if text and len(text.strip()) > 10:
        cleaned = text.strip().replace('"', '')
        # Check that no spurious numbers were introduced
        allowed_nums = {int(stop.venue.rating), int(stop.cost), 5}
        model_nums = _numbers_in(cleaned)
        if model_nums.issubset(allowed_nums | {0, 1, 2}):
            return cleaned[:160]

    # Template fallback
    reasons = []
    if vibe_overlap:
        reasons.append(f"matches your shared love for {', '.join(vibe_overlap)} settings")
    if cuisine_overlap:
        reasons.append(f"features your favored {', '.join(cuisine_overlap)} flavors")
    if not reasons:
        reasons.append(f"offers a standout {stop.venue.rating}★ rating in {stop.venue.area}")

    return f"Selected for {stop.slot.value} because it {' and '.join(reasons)} (approx ₹{stop.cost} for two)."


async def write_itinerary(plan: DatePlan) -> str:
    """Generate friendly itinerary narrative with strict mathematical validation."""
    stops_summary = "\n".join(
        f"- {s.arrival_time} {s.venue.name} ({s.slot.value}): ₹{s.cost}, {s.travel_from_prev_min} min travel"
        for s in plan.stops
    )
    city = plan.stops[0].venue.city if plan.stops else "Tamil Nadu"
    prompt = f"""Write a warm, romantic date itinerary in 3–4 sentences for a couple exploring {city}, Tamil Nadu.
Use ONLY these exact facts:
{stops_summary}
Total budget spent: ₹{plan.total_cost}. Budget remaining: ₹{plan.budget_remaining}. Total travel: {plan.total_travel_min} mins.
Do NOT invent places, prices, or times."""

    allowed_numbers = {plan.total_cost, plan.budget_remaining, plan.total_travel_min}
    for s in plan.stops:
        allowed_numbers.update({s.cost, s.travel_from_prev_min})

    for _ in range(2):
        text = await chat(prompt)
        if text and len(text.strip()) > 30:
            cleaned = text.strip()
            # Validate numbers in LLM text against planner ground truth
            model_nums = _numbers_in(cleaned) - {0, 1, 2, 3, 4, 5, 2024, 2025, 2026}
            if model_nums.issubset(allowed_numbers):
                return cleaned

    # High-quality template narrative fallback
    first = plan.stops[0]
    last = plan.stops[-1]
    lines = [
        f"Your {first.venue.city} date begins at {first.arrival_time} with {first.slot.value} at {first.venue.name} ({first.venue.area}).",
    ]
    for s in plan.stops[1:-1]:
        lines.append(f"Next, enjoy a relaxing {s.slot.value} stop at {s.venue.name}.")
    lines.append(
        f"Wrap up your evening with a memorable {last.slot.value} at {last.venue.name}. "
        f"Total plan spend is ₹{plan.total_cost:,} with ₹{plan.budget_remaining:,} comfortably remaining in your budget."
    )
    return " ".join(lines)
